<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNGk7xPR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNGk7xPR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNGk7xPR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNGk7xPR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNGk7xPR\App_KernelDevDebugContainer([
    'container.build_hash' => 'NGk7xPR',
    'container.build_id' => '5794272f',
    'container.build_time' => 1579289145,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNGk7xPR');
