<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKeDnNvY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKeDnNvY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKeDnNvY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKeDnNvY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKeDnNvY\App_KernelDevDebugContainer([
    'container.build_hash' => 'KeDnNvY',
    'container.build_id' => 'a488c574',
    'container.build_time' => 1579605097,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKeDnNvY');
