<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5sMpD5f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5sMpD5f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5sMpD5f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5sMpD5f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5sMpD5f\App_KernelDevDebugContainer([
    'container.build_hash' => '5sMpD5f',
    'container.build_id' => 'f597ffd7',
    'container.build_time' => 1579252200,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5sMpD5f');
